# Docker Compose override file for development
# This file is automatically loaded by docker-compose and provides development-specific configurations

version: '3.8'

services:
  # Development overrides for the main application
  app:
    build:
      target: development
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DEBUG=*
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./package.json:/app/package.json:ro
      - ./next.config.ts:/app/next.config.ts:ro
      - ./tailwind.config.ts:/app/tailwind.config.ts:ro
      - ./tsconfig.json:/app/tsconfig.json:ro
      # Development logs and storage
      - ./dev-logs:/app/logs
      - ./dev-storage:/app/storage
    ports:
      - "3000:3000"
      - "9229:9229" # Node.js debugger port
    command: npm run dev

  # Development database with exposed port
  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=n8n_converter_dev
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init-db-dev.sql:/docker-entrypoint-initdb.d/01-init-dev.sql:ro

  # Development Redis with exposed port
  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data

  # Disable production services in development
  nginx:
    profiles:
      - production

  prometheus:
    profiles:
      - monitoring

  grafana:
    profiles:
      - monitoring

  loki:
    profiles:
      - monitoring

  promtail:
    profiles:
      - monitoring

  db-backup:
    profiles:
      - production

volumes:
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local