# DigitalOcean App Platform configuration for n8n Workflow Converter
name: n8n-workflow-converter
region: nyc

# Services
services:
  # Main web application
  - name: web
    source_dir: /
    github:
      repo: your-username/n8n-workflow-converter
      branch: main
      deploy_on_push: true
    
    # Build configuration
    build_command: npm run build
    run_command: npm start
    
    # Environment
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Health check
    health_check:
      http_path: /api/health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # HTTP configuration
    http_port: 3000
    
    # Environment variables
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: NEXTAUTH_URL
        value: ${APP_URL}
      - key: NEXTAUTH_SECRET
        value: ${NEXTAUTH_SECRET}
        type: SECRET
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        value: ${redis.REDIS_URL}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
        type: SECRET
      - key: ANTHROPIC_API_KEY
        value: ${ANTHROPIC_API_KEY}
        type: SECRET
      - key: GOOGLE_AI_API_KEY
        value: ${GOOGLE_AI_API_KEY}
        type: SECRET
      - key: VIRUSTOTAL_API_KEY
        value: ${VIRUSTOTAL_API_KEY}
        type: SECRET
      - key: ENCRYPTION_KEY
        value: ${ENCRYPTION_KEY}
        type: SECRET
      - key: SENTRY_DSN
        value: ${SENTRY_DSN}
        type: SECRET
    
    # Routes
    routes:
      - path: /
        preserve_path_prefix: true

# Databases
databases:
  - name: db
    engine: PG
    version: "15"
    size: basic-xs
    num_nodes: 1
    
# Workers (for background jobs)
workers:
  - name: cleanup-worker
    source_dir: /
    github:
      repo: your-username/n8n-workflow-converter
      branch: main
    build_command: npm run build
    run_command: npm run worker:cleanup
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: REDIS_URL
        value: ${redis.REDIS_URL}

# Static sites (for documentation)
static_sites:
  - name: docs
    source_dir: /docs
    github:
      repo: your-username/n8n-workflow-converter
      branch: main
    build_command: |
      # Build documentation site
      npm install -g @11ty/eleventy
      eleventy --input=docs --output=_site
    output_dir: _site
    index_document: index.html
    error_document: 404.html
    routes:
      - path: /docs
        preserve_path_prefix: false

# Jobs (for one-time tasks)
jobs:
  - name: db-migrate
    source_dir: /
    github:
      repo: your-username/n8n-workflow-converter
      branch: main
    build_command: npm ci
    run_command: npm run migrate
    environment_slug: node-js
    instance_size_slug: basic-xxs
    kind: PRE_DEPLOY
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}

# Functions (serverless functions)
functions:
  - name: webhook-handler
    source_dir: /functions
    github:
      repo: your-username/n8n-workflow-converter
      branch: main
    routes:
      - path: /webhooks
        preserve_path_prefix: true
    envs:
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: WEBHOOK_SECRET
        value: ${WEBHOOK_SECRET}
        type: SECRET

# Alerts
alerts:
  - rule: CPU_UTILIZATION
    disabled: false
    value: 80
    operator: GREATER_THAN
    window: FIVE_MINUTES
    
  - rule: MEM_UTILIZATION
    disabled: false
    value: 85
    operator: GREATER_THAN
    window: FIVE_MINUTES
    
  - rule: RESTART_COUNT
    disabled: false
    value: 5
    operator: GREATER_THAN
    window: FIVE_MINUTES

# Domains (configure after deployment)
domains:
  - domain: your-domain.com
    type: PRIMARY
    wildcard: false
    certificate_id: ""
    
  - domain: www.your-domain.com
    type: ALIAS
    wildcard: false
    certificate_id: ""